---
default_stages: [commit]
repos:
  - repo: local
    hooks:
      - id: deploy
        name: deploy
        always_run: true
        stages: [post-commit]
        language: system
        entry: >-
          bash -c 'rsync -azvc --delete --exclude .git/
          ./ barklan:static/common'
