---
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: check-json
        exclude: ".vscode/tasks.json"
      - id: check-case-conflict
      - id: check-symlinks
      - id: mixed-line-ending
        args: ["--fix=no"]
      - id: no-commit-to-branch
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.27.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint
        args:
          [
            "--ignore=body-is-missing,body-min-length",
            "--contrib=contrib-title-conventional-commits",
            "--msg-filename",
          ]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        exclude: "^go.sum"
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        exclude: ".*_test.go$"
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.8.7
    hooks:
      - id: gitleaks
  - repo: https://github.com/yoheimuta/protolint
    rev: v0.38.1
    hooks:
      - id: protolint
  - repo: https://github.com/hadolint/hadolint
    rev: v2.10.0
    hooks:
      - id: hadolint
  - repo: https://github.com/barklan/git-hooks
    rev: v0.1.2
    hooks:
      - id: go-test
      - id: go-format
      - id: forbid-binary
      - id: docker-compose-check
      - id: snake-case-filenames
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 0.13.2
    hooks:
      - id: sqlfluff-lint
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.16.0
    hooks:
      - id: check-github-workflows
      - id: check-gitlab-ci
      - id: check-github-actions
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
        args:
          - "--disable=MD013"
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.72.1
    hooks:
      - id: terraform_validate
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v6.3.0
    hooks:
      - id: ansible-lint
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [css, javascript, ts, vue, html, scss, yaml]

  # NOTE: require docker
  - repo: local
    hooks:
      - id: dotenv-linter
        name: run dotenv linter
        language: docker_image
        entry: dotenvlinter/dotenv-linter --recursive
        files: \.env$
      - id: openapi-linter
        name: validate openapi schema
        language: docker_image
        entry: redocly/openapi-cli lint docs/openapi.yml
        files: ^docs/openapi.yml$

  # Post-commit
  - repo: local
    hooks:
      - id: post-commit-local
        name: post commit
        always_run: true
        stages: [post-commit]
        language: system
        entry: >-
          bash -c 'hugo --gc --minify && rsync -azvc --delete
          public/ barklan:static/notes'

  # Go specific
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.46.2
    hooks:
      - id: golangci-lint

  # Lua specific
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.13.1
    hooks:
      - id: stylua

  # Python specific
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - --profile=black
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
        additional_dependencies: [flake8-eradicate, flake8-pytest-style]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        exclude: "_test.py$|test_.*.py$"
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks
  autofix_prs: false
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: quarterly
  # These require either docker or docker-compose.
  # Use separate job for golangci-lint.
  skip: [dotenv-linter, openapi-linter, docker-compose-check, golangci-lint]
  submodules: false
